import { requireUser } from "@/lib/auth/permissions";
import { createAdminClient } from "@/lib/supabase/admin";
import { createWarehouse, toggleWarehouse, updateWarehouseStorageRate } from "./actions";

export default async function WarehousesPage() {
  const { profile } = await requireUser();
  if (profile?.role !== "finance_admin") throw new Error("Forbidden");
  const { data: warehouses, error } = await createAdminClient().from("warehouses").select("id, name, location, storage_rate_aed_per_cbm_day, active").order("name");
  if (error) throw new Error(error.message);
  return <div className="p-8"><div className="mb-8"><h1 className="text-2xl font-semibold">Warehouses</h1><p className="mt-1 text-sm text-zinc-500">Set storage rates and maintain warehouse locations used by purchasing and costing.</p></div>
    <section className="mb-8 rounded-xl border bg-white p-6 shadow-sm"><h2 className="mb-4 font-semibold">Add Warehouse</h2><form action={createWarehouse} className="grid gap-3 md:grid-cols-3"><input name="name" required placeholder="Warehouse name" className="rounded-lg border px-3 py-2.5 text-sm"/><input name="location" placeholder="Location" className="rounded-lg border px-3 py-2.5 text-sm"/><input name="storageRate" required type="number" min="0" step="0.0001" placeholder="AED / CBM / Day" className="rounded-lg border px-3 py-2.5 text-sm"/><button className="rounded-lg bg-zinc-900 px-4 py-2.5 text-sm font-medium text-white md:w-fit">Add Warehouse</button></form></section>
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><table className="w-full text-sm"><thead className="border-b bg-zinc-50"><tr><th className="px-5 py-3 text-left">Warehouse</th><th className="px-5 py-3 text-left">Location</th><th className="px-5 py-3 text-right">AED / CBM / Day</th><th className="px-5 py-3">Active</th><th className="px-5 py-3"/></tr></thead><tbody className="divide-y">{(warehouses ?? []).map((warehouse) => <tr key={warehouse.id}><td className="px-5 py-4 font-medium">{warehouse.name}</td><td className="px-5 py-4">{warehouse.location ?? "—"}</td><td className="px-5 py-4"><form id={`warehouse-${warehouse.id}`} action={updateWarehouseStorageRate} className="flex justify-end gap-2"><input type="hidden" name="warehouseId" value={warehouse.id}/><input name="storageRate" type="number" min="0" step="0.0001" defaultValue={Number(warehouse.storage_rate_aed_per_cbm_day)} className="w-36 rounded-lg border px-3 py-2 text-right"/><button className="rounded-lg bg-zinc-900 px-3 py-2 text-xs font-medium text-white">Save</button></form></td><td className="px-5 py-4 text-center text-xs">{warehouse.active ? "Yes" : "No"}</td><td className="px-5 py-4 text-right"><form action={toggleWarehouse}><input type="hidden" name="warehouseId" value={warehouse.id}/><input type="hidden" name="active" value={String(warehouse.active)}/><button className="text-xs text-zinc-500 hover:text-zinc-900">{warehouse.active ? "Deactivate" : "Activate"}</button></form></td></tr>)}</tbody></table></section>
  </div>;
}
