-- Initial master-data seed generated from Costing v2.xlsx
-- No customers/users are invented because the workbook does not contain a clean customer master.
-- Run after schema.sql.

begin;

-- Suppliers

insert into public.suppliers (name) values ('China-Base Ningbo') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Chori Japan') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Chori Singapore') on conflict (name) do nothing;
insert into public.suppliers (name) values ('GC Polyols') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Inoac') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Kromatiks') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Lulu Chem') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Marubeni') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Momentive') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Nanjing Chenxu') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Ningbo HFC Chemi') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Polyols & Polymers') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Prakash Chemicals') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Shin Etsu') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Tosoh') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Zeon') on conflict (name) do nothing;
insert into public.suppliers (name) values ('Zhejiang Wansheng') on conflict (name) do nothing;

-- Vehicle types

insert into public.vehicle_types (code, name, capacity_kg) values ('1T', '1 Ton', 1000) on conflict (code) do nothing;
insert into public.vehicle_types (code, name, capacity_kg) values ('3T', '3 Ton', 3000) on conflict (code) do nothing;
insert into public.vehicle_types (code, name, capacity_kg) values ('7T', '7 Ton', 7000) on conflict (code) do nothing;
insert into public.vehicle_types (code, name, capacity_kg) values ('10T', '10 Ton', 10000) on conflict (code) do nothing;
insert into public.vehicle_types (code, name, capacity_kg) values ('TRAILER_20', 'Trailer 20"', NULL) on conflict (code) do nothing;

-- Incoterms

insert into public.incoterms (code, name, delivery_type) values ('DDP', 'Delivered Duty Paid', 'local'::public.delivery_type) on conflict (code) do nothing;
insert into public.incoterms (code, name, delivery_type) values ('DDU', 'Delivered Duty Unpaid', 'local'::public.delivery_type) on conflict (code) do nothing;
insert into public.incoterms (code, name, delivery_type) values ('EXW', 'Ex Works', NULL) on conflict (code) do nothing;
insert into public.incoterms (code, name, delivery_type) values ('TOO', 'Transfer of Ownership', 'local'::public.delivery_type) on conflict (code) do nothing;
insert into public.incoterms (code, name, delivery_type) values ('FOB', 'Free On Board', NULL) on conflict (code) do nothing;
insert into public.incoterms (code, name, delivery_type) values ('CIF', 'Cost, Insurance and Freight', 'export'::public.delivery_type) on conflict (code) do nothing;
insert into public.incoterms (code, name, delivery_type) values ('CFR', 'Cost and Freight', 'export'::public.delivery_type) on conflict (code) do nothing;
insert into public.incoterms (code, name, delivery_type) values ('3RD_PORT', '3rd Port', 'export'::public.delivery_type) on conflict (code) do nothing;
insert into public.incoterms (code, name, delivery_type) values ('DAP', 'Delivered At Place', 'export'::public.delivery_type) on conflict (code) do nothing;

-- Payment terms

insert into public.payment_terms (code, name, default_credit_days) values ('CASH_ADVANCE', 'Cash Advance', 0) on conflict (code) do nothing;
insert into public.payment_terms (code, name, default_credit_days) values ('PDC', 'PDC', 0) on conflict (code) do nothing;
insert into public.payment_terms (code, name, default_credit_days) values ('CDC', 'CDC', 0) on conflict (code) do nothing;
insert into public.payment_terms (code, name, default_credit_days) values ('DA', 'DA', 0) on conflict (code) do nothing;
insert into public.payment_terms (code, name, default_credit_days) values ('LC', 'LC', 0) on conflict (code) do nothing;
insert into public.payment_terms (code, name, default_credit_days) values ('BANK_AVALIZED_DRAFT', 'Bank Avalized Draft', 0) on conflict (code) do nothing;
insert into public.payment_terms (code, name, default_credit_days) values ('TT', 'TT', 0) on conflict (code) do nothing;

-- Destinations from the transport matrix / costing template

insert into public.destinations (code, name, region, delivery_type) values ('EXPORT', 'Export', 'international', 'export'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('3RD_PORT', '3rd Port', 'international', 'export'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('JAFZA', 'JAFZA', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('DWC', 'DWC', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('DIP', 'DIP', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('DIC', 'DIC', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('DUBAI', 'Dubai', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('SHARJAH', 'Sharjah', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('SHARJAH_FREEZONE', 'Sharjah Freezone', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('SAIF_ZONE', 'Saif Zone', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('AJMAN', 'Ajman', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('UAQ', 'UAQ', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('RAK', 'RAK', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('RAK_AL_GHAIL', 'RAK Al Ghail', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('KHALIFA_PORT', 'Khalifa Port', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('AUH_MIUSSAFAH', 'AUH - MIUSSAFAH', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('AUH_CITY', 'AUH - CITY', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('AUH_KIZAD', 'AUH - KIZAD', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('AL_AIN', 'Al-Ain', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('FUJAIRAH', 'Fujairah', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;
insert into public.destinations (code, name, region, delivery_type) values ('ABU_DHABI', 'Abu Dhabi', 'local', 'local'::public.delivery_type) on conflict (code) do update set name=excluded.name;

-- Global settings

insert into public.global_settings (setting_key, setting_value, description) values ('usd_to_aed_conversion', 3.6725, 'USD to AED conversion rate') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('annual_interest_rate', 0.1, 'Annual capital/opportunity interest rate') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('customs_duty_pct', 0.05, 'Customs duty percentage') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('tt_bank_flat_fee', 30, 'Supplier TT bank charge, flat AED') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('da_bank_fee_pct', 0.0024, 'Supplier DA charge as a percentage of supplier invoice value') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('lc_sight_pct', 0.0088, 'Supplier LC at sight rate') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('lc_30_pct', 0.0113, 'Supplier LC 30 day rate') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('lc_60_pct', 0.015, 'Supplier LC 60 day rate') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('lc_90_pct', 0.0188, 'Supplier LC 90 day rate') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('lc_120_pct', 0.0225, 'Supplier LC 120 day rate') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('customer_da_flat_fee', 800, 'Customer DA bank charge') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('customer_lc_flat_fee', 800, 'Customer LC fixed component') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('customer_lc_value_pct', 0.0055, 'Customer LC percentage of sales/invoice value') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('customer_bank_draft_flat_fee', 900, 'Customer bank avalized draft fixed charge') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('marine_insurance_base_pct', 0.0007, 'Marine insurance base rate before insured value multiplier') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('marine_insurance_cif_multiplier', 1.1, 'CIF / 3rd port insured value multiplier') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('marine_insurance_fob_multiplier', 1.2, 'FOB insured value multiplier') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('courier_local_aed', 15, 'Courier/other expense for local TT customer') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('courier_gcc_aed', 210, 'Courier/other expense for GCC TT customer') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('courier_africa_aed', 525, 'Courier/other expense for Africa TT customer') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('dwc_surcharge_under_7t', 50, 'DWC transport surcharge for pickups up to 7T') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;
insert into public.global_settings (setting_key, setting_value, description) values ('dwc_surcharge_over_7t', 100, 'DWC transport surcharge for pickups above 7T') on conflict (setting_key) do update set setting_value=excluded.setting_value, description=excluded.description;

-- Insurance rules

insert into public.insurance_rules (incoterm_code, base_rate_pct, insured_value_multiplier, notes) values ('CIF', 0.0007, 1.10, 'Workbook rule: 0.07% of 110% of invoice/sales value'), ('3RD_PORT', 0.0007, 1.10, 'Workbook rule: 0.07% of 110% of invoice/sales value'), ('FOB', 0.0007, 1.20, 'Workbook rule: 0.07% of 120% of invoice/sales value');

-- Supplier-side bank fee rules

insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('supplier','TT',NULL,30,0,'Flat AED 30');
insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('supplier','DA',NULL,0,0.0024,'0.24% of supplier invoice value');
insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('supplier','LC',0,0,0.0088,'LC at Sight');
insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('supplier','LC',30,0,0.0113,'LC 30 days');
insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('supplier','LC',60,0,0.015,'LC 60 days');
insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('supplier','LC',90,0,0.0188,'LC 90 days');
insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('supplier','LC',120,0,0.0225,'LC 120 days');
insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('customer','DA',NULL,800,0,'450 + 350');
insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('customer','LC',NULL,800,0.0055,'350 + 450 + 0.55% of invoice value');
insert into public.bank_fee_rules (side,payment_term_code,credit_days,flat_fee_aed,value_pct,notes) values ('customer','BANK_AVALIZED_DRAFT',NULL,900,0,'450 + 100 + 350');

-- Products and supplier references

insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (1,'Alkyl Phenolic Resin','Import',8000,2.61,5.0,1955,0.55,90,(select id from public.suppliers where name = 'Polyols & Polymers' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (2,'Catalyst DBTDL','Import',16000,12,5.0,3424,1.7,90,(select id from public.suppliers where name = 'Nanjing Chenxu' limit 1),'TT',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (3,'Catalyst DMEA','Import',14400,2.2,5.0,3424,1.7,90,(select id from public.suppliers where name = 'Nanjing Chenxu' limit 1),'TT',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (4,'Catalyst FC 312','Import',17640,10.5,5.0,3074,2.1,90,(select id from public.suppliers where name = 'Nanjing Chenxu' limit 1),'TT',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (5,'Catalyst Polycat 5 (PMDETA)','Import',13600,5.2,5.0,3424,1.7,90,(select id from public.suppliers where name = 'Nanjing Chenxu' limit 1),'TT',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (6,'Catalyst Polycat 8 (DMCHA)','Import',13600,2.3,5.0,3424,1.7,90,(select id from public.suppliers where name = 'Nanjing Chenxu' limit 1),'TT',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (7,'CHN-9300-U','Import',14400,4.5,5.0,3074,2.1,90,(select id from public.suppliers where name = 'Shin Etsu' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (8,'CHN-9700-U (SILICONE RUBBER)','Import',14400,3.1,5.0,3074,2.1,90,(select id from public.suppliers where name = 'Shin Etsu' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (9,'Denka Chloroprene Rubber A90','Import',16000,6.3,5.0,2974,NULL,90,(select id from public.suppliers where name = 'Chori Japan' limit 1),'TT',120);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (10,'Denka Chloroprene Rubber M130H','Import',16000,6.3,5.0,2974,NULL,90,(select id from public.suppliers where name = 'Chori Japan' limit 1),'TT',120);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (11,'Denka Chloroprene Rubber M130L','Import',16000,6.3,5.0,2974,NULL,90,(select id from public.suppliers where name = 'Chori Japan' limit 1),'TT',120);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (12,'Di Propylene Glycol','Local',840,3.75,5.0,0,NULL,0,(select id from public.suppliers where name = 'Lulu Chem' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (13,'Diethanol Amine (99%)','Local',900,2.07,5.0,0,NULL,0,(select id from public.suppliers where name = 'Lulu Chem' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (14,'Dioctyl-phthalate (DOP)','Local',800,2.66,5.0,0,NULL,0,(select id from public.suppliers where name = 'Lulu Chem' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (15,'Flame Retardant WSFR504L','Import',4000,3.08,5.0,3455,NULL,90,(select id from public.suppliers where name = 'Zhejiang Wansheng' limit 1),'TT',0);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (16,'Glycerin','Local',1000,1.6,5.0,0,NULL,0,(select id from public.suppliers where name = 'Lulu Chem' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (17,'Gum Rosin','Import',19200,1.32,5.0,2974,NULL,90,(select id from public.suppliers where name = 'Chori Singapore' limit 1),'TT',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (18,'Magnesium Oxide - Starmag 150','Import',10400,1.9,5.0,2974,NULL,90,(select id from public.suppliers where name = 'Chori Japan' limit 1),'TT',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (19,'Methylene Chloride','Import',20000,0.5,5.0,3744,NULL,60,(select id from public.suppliers where name = 'Prakash Chemicals' limit 1),'TT',0);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (20,'NBR DN4050 - Direct dellivery to cu','Import',21360,2.8,5.0,2274,2.1,0,(select id from public.suppliers where name = 'Zeon' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (21,'NBR Nipol DN 219 - Direct delivery','Import',21360,2.5,5.0,2274,2.1,0,(select id from public.suppliers where name = 'Zeon' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (22,'Niax Amine Catalyst A1','Import',12000,17.5,5.0,3874,0.55,150,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (23,'Niax Amine Catalyst DMEA','Import',3600,5.75,5.0,3424,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (24,'Niax Catalyst A230','Import',11520,11.25,5.0,3544,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (25,'Niax Catalyst A33','Import',12000,7,5.0,3544,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (26,'Niax Catalyst C5 (PMEDTA)','Import',3400,7.3,5.0,3424,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (27,'Niax Catalyst D19','Import',16000,18.4,5.0,3544,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (28,'Niax Catalyst D25','Import',16000,19.25,5.0,3544,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (29,'Niax Catalyst LC5604 (SUL4 DBTD','Import',2880,22.75,5.0,3424,0.55,150,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (30,'Niax Catalyst SA200','Import',3680,10.85,5.0,3424,0.55,150,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (31,'Niax Color Paste Blue 614','Import',6000,11,5.0,3544,0.55,150,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (32,'Niax Color Paste Green','Import',6000,11,5.0,3544,0.55,150,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (33,'Niax Color Stabilizer CS16','Import',6000,12,5.0,3544,0.55,150,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (34,'Niax DP1022','Import',16000,5.1,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (35,'Niax Foam Hardner FH300','Import',16000,4.25,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (36,'Niax Foam Hardner FH400','Import',16800,4.5,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (37,'Niax Geolite Modifier 210','Import',17440,9.5,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (38,'Niax Silicone L2112','Import',15600,12,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (39,'Niax Silicone L450','Import',14400,16.5,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (40,'Niax Silicone L565','Import',16800,5.15,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (41,'Niax Silicone L570','Import',16800,6,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (42,'Niax Silicone L580','Import',16800,5.25,5.0,3544,0.55,60,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (43,'Niax Silicone L581','Import',17040,4.26,5.0,3544,0.55,180,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (44,'Niax Silicone L591','Import',16800,4.6,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (45,'Niax Silicone L594','Import',16000,5.75,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (46,'Niax Silicone L618','Import',16800,5.5,5.0,3544,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (47,'Niax Silicone L690','Import',16800,4.12,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (48,'Niax Silicone L6900','Import',16800,4.1,5.0,3544,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (49,'Niax Silicone L6970','Import',4160,7.05,5.0,3424,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (50,'Niax Silicone SC200','Import',1,250,5.0,3544,0.55,120,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (51,'Niax Silicone SR321','Import',16800,4.1,5.0,3544,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (52,'Niax Stannous Octoate','Import',16000,18.4,5.0,3544,0.55,90,(select id from public.suppliers where name = 'Momentive' limit 1),'DA',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (53,'Petroleum Resin C9','Import',18000,1.12,5.0,4424,NULL,150,(select id from public.suppliers where name = 'Kromatiks' limit 1),'TT',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (54,'Pigment Black 124','Import',1200,6.25,5.0,1755,NULL,120,(select id from public.suppliers where name = 'Kromatiks' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (55,'Pigment Blue 306','Import',1200,4.15,5.0,1755,NULL,120,(select id from public.suppliers where name = 'Kromatiks' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (56,'Pigment Fire Red 412','Import',1200,4.7,5.0,1755,NULL,120,(select id from public.suppliers where name = 'Kromatiks' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (57,'Pigment Golden Yellow 605','Import',1200,4.2,5.0,1755,NULL,120,(select id from public.suppliers where name = 'Kromatiks' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (58,'Pigment Green 205','Import',1200,4.1,5.0,1755,NULL,120,(select id from public.suppliers where name = 'Kromatiks' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (59,'Pigment Yellow 600','Import',1200,4.15,5.0,1755,NULL,120,(select id from public.suppliers where name = 'Kromatiks' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (60,'Pigment Yellow 606','Import',1200,4.25,5.0,1755,NULL,120,(select id from public.suppliers where name = 'Kromatiks' limit 1),'TT',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (61,'Polymeric MDI (MR-200)','Import',19500,2.05,5.0,3544,2.1,30,(select id from public.suppliers where name = 'Tosoh' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (62,'Polymeric MDI (MR-200) - 3rd port','Import',19500,2.05,5.0,0,2.1,0,(select id from public.suppliers where name = 'Tosoh' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (63,'Polymeric MDI (MR-200) - Direct to','Import',19500,2.05,5.0,2644,2.1,0,(select id from public.suppliers where name = 'Tosoh' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (64,'Polyol (Actcol LR00)','Import',16000,2.7,5.0,3074,2.46,60,(select id from public.suppliers where name = 'Chori Japan' limit 1),'TT',120);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (65,'Polyol (Actcol LR00) - Direct to loca','Import',16000,2.7,5.0,2174,2.46,0,(select id from public.suppliers where name = 'Chori Japan' limit 1),'L/C',120);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (66,'Polyol Genix FA703','Import',16400,1.42,5.0,2974,1.34,60,(select id from public.suppliers where name = 'GC Polyols' limit 1),'L/C',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (67,'Polyol Genix FM-5900','Import',16800,1.93,5.0,2974,1.34,60,(select id from public.suppliers where name = 'GC Polyols' limit 1),'L/C',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (68,'Polyol Genix HS209','Import',17600,1.32,5.0,2974,1.34,60,(select id from public.suppliers where name = 'GC Polyols' limit 1),'L/C',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (69,'Polyol Genix KC900','Import',16800,1.84,5.0,2974,1.34,60,(select id from public.suppliers where name = 'GC Polyols' limit 1),'L/C',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (70,'Polyol Genix MH204','Import',16000,1.53,5.0,2974,1.34,60,(select id from public.suppliers where name = 'GC Polyols' limit 1),'L/C',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (71,'Polyol Genix MH204 - 3rd port','Import',16000,1.53,5.0,0,1.34,0,(select id from public.suppliers where name = 'GC Polyols' limit 1),'L/C',30);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (72,'Polyvinyl Alcohol 24-88','Import',19000,1.98,5.0,2974,NULL,150,(select id from public.suppliers where name = 'Ningbo HFC Chemi' limit 1),'TT',120);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (73,'Polyvinyl Alcohol Gohsenol GH17R','Import',14400,1.93,5.0,2974,2.1,90,(select id from public.suppliers where name = 'Marubeni' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (74,'Polyvinyl Alcohol Gohsenol GH20R','Import',14400,1.93,5.0,2974,2.1,90,(select id from public.suppliers where name = 'Marubeni' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (75,'Polyvinyl Alcohol Gohsenol GH22','Import',14400,1.93,5.0,2974,2.1,90,(select id from public.suppliers where name = 'Marubeni' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (76,'Polyvinyl Alcohol Gohsenol GL05','Import',14400,1.93,5.0,2974,2.1,90,(select id from public.suppliers where name = 'Marubeni' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (77,'PU Trim Foam','Import',22000,0.47,5.0,2974,NULL,0,(select id from public.suppliers where name = 'Inoac' limit 1),'TT',0);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (78,'SBR1502','Import',20160,2.45,5.0,2974,2.1,120,(select id from public.suppliers where name = 'Zeon' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (79,'Silica Gel Powder(Blue)','Import',1000,3.14,5.0,1880,NULL,180,(select id from public.suppliers where name = 'China-Base Ningbo' limit 1),'TT',0);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (80,'Silicone Sealant FC 295 SG','Import',16947,4.3,5.0,3174,2.1,60,(select id from public.suppliers where name = 'Shin Etsu' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (81,'Silicone Catalyst  FC 295 SG','Import',16947,11.6,5.0,3174,2.1,60,(select id from public.suppliers where name = 'Shin Etsu' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (82,'Silicone Sealant 90N','Import',16000,5.3,5.0,3174,2.1,60,(select id from public.suppliers where name = 'Shin Etsu' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (83,'Silicone Sealant 72N','Import',16000,3.95,5.0,3174,2.1,60,(select id from public.suppliers where name = 'Shin Etsu' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (84,'Silicone Sealant FC 312','Import',17640,3.1,5.0,3174,2.1,120,(select id from public.suppliers where name = 'Shin Etsu' limit 1),'L/C',90);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (85,'TDI 80/20 (Toluene Diisocyanate )','Import',19750,1.95,5.0,3424,2.46,15,(select id from public.suppliers where name = 'Chori Japan' limit 1),'L/C',120);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (86,'TDI 80/20 (Toluene Diisocyanate ) -','Import',19750,1.95,5.0,0,2.46,0,(select id from public.suppliers where name = 'Chori Japan' limit 1),'L/C',120);
insert into public.products (excel_reference_no,name,supply_type,pack_size_kg,cif_rate_usd,default_profit_pct,inward_clearance_charge,storage_rate,storage_days,supplier_id,supplier_mop,supplier_credit_days) values (87,'TDI 80/20 (Toluene Diisocyanate ) -','Import',19750,1.95,5.0,2524,2.46,0,(select id from public.suppliers where name = 'Chori Japan' limit 1),'L/C',120);

-- Transport rates

insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='JAFZA' limit 1),(select id from public.vehicle_types where code='1T' limit 1),125);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='JAFZA' limit 1),(select id from public.vehicle_types where code='3T' limit 1),150);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='JAFZA' limit 1),(select id from public.vehicle_types where code='7T' limit 1),250.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='JAFZA' limit 1),(select id from public.vehicle_types where code='10T' limit 1),300.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='JAFZA' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),375.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DWC' limit 1),(select id from public.vehicle_types where code='1T' limit 1),150);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DWC' limit 1),(select id from public.vehicle_types where code='3T' limit 1),200);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DWC' limit 1),(select id from public.vehicle_types where code='7T' limit 1),325.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DWC' limit 1),(select id from public.vehicle_types where code='10T' limit 1),350.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DWC' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),450.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIP' limit 1),(select id from public.vehicle_types where code='1T' limit 1),175);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIP' limit 1),(select id from public.vehicle_types where code='3T' limit 1),250);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIP' limit 1),(select id from public.vehicle_types where code='7T' limit 1),400.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIP' limit 1),(select id from public.vehicle_types where code='10T' limit 1),425.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIP' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),500.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIC' limit 1),(select id from public.vehicle_types where code='1T' limit 1),250);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIC' limit 1),(select id from public.vehicle_types where code='3T' limit 1),350);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIC' limit 1),(select id from public.vehicle_types where code='7T' limit 1),450.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIC' limit 1),(select id from public.vehicle_types where code='10T' limit 1),475.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DIC' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),600.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DUBAI' limit 1),(select id from public.vehicle_types where code='1T' limit 1),275);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DUBAI' limit 1),(select id from public.vehicle_types where code='3T' limit 1),300);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DUBAI' limit 1),(select id from public.vehicle_types where code='7T' limit 1),500.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DUBAI' limit 1),(select id from public.vehicle_types where code='10T' limit 1),525.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='DUBAI' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),650.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SHARJAH' limit 1),(select id from public.vehicle_types where code='1T' limit 1),300);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SHARJAH' limit 1),(select id from public.vehicle_types where code='3T' limit 1),350);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SHARJAH' limit 1),(select id from public.vehicle_types where code='7T' limit 1),550.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SHARJAH' limit 1),(select id from public.vehicle_types where code='10T' limit 1),525.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SHARJAH' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),750.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SAIF_ZONE' limit 1),(select id from public.vehicle_types where code='1T' limit 1),325);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SAIF_ZONE' limit 1),(select id from public.vehicle_types where code='3T' limit 1),375);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SAIF_ZONE' limit 1),(select id from public.vehicle_types where code='7T' limit 1),630.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SAIF_ZONE' limit 1),(select id from public.vehicle_types where code='10T' limit 1),655.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='SAIF_ZONE' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),830.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AJMAN' limit 1),(select id from public.vehicle_types where code='1T' limit 1),350);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AJMAN' limit 1),(select id from public.vehicle_types where code='3T' limit 1),400);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AJMAN' limit 1),(select id from public.vehicle_types where code='7T' limit 1),970.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AJMAN' limit 1),(select id from public.vehicle_types where code='10T' limit 1),995.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AJMAN' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),1370.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='UAQ' limit 1),(select id from public.vehicle_types where code='1T' limit 1),375);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='UAQ' limit 1),(select id from public.vehicle_types where code='3T' limit 1),450);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='UAQ' limit 1),(select id from public.vehicle_types where code='7T' limit 1),1020.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='UAQ' limit 1),(select id from public.vehicle_types where code='10T' limit 1),1045.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='UAQ' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),1425.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK' limit 1),(select id from public.vehicle_types where code='1T' limit 1),400);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK' limit 1),(select id from public.vehicle_types where code='3T' limit 1),500);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK' limit 1),(select id from public.vehicle_types where code='7T' limit 1),1170.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK' limit 1),(select id from public.vehicle_types where code='10T' limit 1),1195.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),2070.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK_AL_GHAIL' limit 1),(select id from public.vehicle_types where code='1T' limit 1),500);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK_AL_GHAIL' limit 1),(select id from public.vehicle_types where code='3T' limit 1),600);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK_AL_GHAIL' limit 1),(select id from public.vehicle_types where code='7T' limit 1),1270.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK_AL_GHAIL' limit 1),(select id from public.vehicle_types where code='10T' limit 1),1320.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='RAK_AL_GHAIL' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),2170.5);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_MIUSSAFAH' limit 1),(select id from public.vehicle_types where code='1T' limit 1),500);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_MIUSSAFAH' limit 1),(select id from public.vehicle_types where code='3T' limit 1),600);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_MIUSSAFAH' limit 1),(select id from public.vehicle_types where code='7T' limit 1),900.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_MIUSSAFAH' limit 1),(select id from public.vehicle_types where code='10T' limit 1),925.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_MIUSSAFAH' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),1200.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_CITY' limit 1),(select id from public.vehicle_types where code='1T' limit 1),500);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_CITY' limit 1),(select id from public.vehicle_types where code='3T' limit 1),600);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_CITY' limit 1),(select id from public.vehicle_types where code='7T' limit 1),900.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_CITY' limit 1),(select id from public.vehicle_types where code='10T' limit 1),925.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_CITY' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),1300.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_KIZAD' limit 1),(select id from public.vehicle_types where code='1T' limit 1),400);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_KIZAD' limit 1),(select id from public.vehicle_types where code='3T' limit 1),500);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_KIZAD' limit 1),(select id from public.vehicle_types where code='7T' limit 1),900.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_KIZAD' limit 1),(select id from public.vehicle_types where code='10T' limit 1),925.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AUH_KIZAD' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),1100.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AL_AIN' limit 1),(select id from public.vehicle_types where code='1T' limit 1),550);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AL_AIN' limit 1),(select id from public.vehicle_types where code='3T' limit 1),650);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AL_AIN' limit 1),(select id from public.vehicle_types where code='7T' limit 1),900.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AL_AIN' limit 1),(select id from public.vehicle_types where code='10T' limit 1),925.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='AL_AIN' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),1400.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='FUJAIRAH' limit 1),(select id from public.vehicle_types where code='1T' limit 1),550);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='FUJAIRAH' limit 1),(select id from public.vehicle_types where code='3T' limit 1),700);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='FUJAIRAH' limit 1),(select id from public.vehicle_types where code='7T' limit 1),1100.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='FUJAIRAH' limit 1),(select id from public.vehicle_types where code='10T' limit 1),1150.0);
insert into public.transport_rates (destination_id,vehicle_type_id,rate_aed) values ((select id from public.destinations where code='FUJAIRAH' limit 1),(select id from public.vehicle_types where code='TRAILER_20' limit 1),1550.0);

-- DWC surcharge rules from workbook note.
insert into public.transport_surcharges
(destination_id,name,condition_type,threshold_kg,surcharge_aed,notes)
values
((select id from public.destinations where code='DWC'),
 'DWC pickup surcharge up to 7T','vehicle_capacity_lte',7000,50,
 'Additional AED 50 for transportation to/from DWC for pickups up to 7T'),
((select id from public.destinations where code='DWC'),
 'DWC pickup surcharge above 7T','vehicle_capacity_gt',7000,100,
 'Additional AED 100 for transportation to/from DWC for pickups above 7T');

-- One default warehouse for the demo.
insert into public.warehouses (name, location)
values ('Main Warehouse', 'Dubai')
on conflict (name) do nothing;

commit;
