import { requireUser } from "@/lib/auth/permissions";
import { createAdminClient } from "@/lib/supabase/admin";
import { createProduct, toggleProduct, updateProduct } from "./actions";

export default async function ProductsAdminPage() {
  const { profile } = await requireUser();
  if (profile?.role !== "finance_admin") throw new Error("Forbidden");
  const admin = createAdminClient();
  const [{ data: products, error: productsError }, { data: suppliers, error: suppliersError }] = await Promise.all([
    admin.from("products").select("id, name, supply_type, pack_size_kg, cif_rate_usd, default_profit_pct, inward_clearance_charge, storage_rate, storage_days, supplier_id, supplier_mop, supplier_credit_days, active").order("name"),
    admin.from("suppliers").select("id, name").order("name"),
  ]);
  if (productsError) throw new Error(productsError.message);
  if (suppliersError) throw new Error(suppliersError.message);

  const input = "rounded-lg border px-2.5 py-2 text-sm";
  return <div className="p-8">
    <div className="mb-8"><h1 className="text-2xl font-semibold">Products</h1><p className="mt-1 text-sm text-zinc-500">Maintain product master data used by purchasing and costing.</p></div>
    <section className="mb-8 rounded-xl border bg-white p-6 shadow-sm"><h2 className="mb-4 font-semibold">Add Product</h2><form action={createProduct} className="grid gap-3 md:grid-cols-4 lg:grid-cols-6">
      <input name="name" required placeholder="Product name" className={input}/><input name="supplyType" required placeholder="Supply type" className={input}/><input name="packSizeKg" required type="number" min="0.01" step="0.01" placeholder="Pack kg" className={input}/><input name="cifRateUsd" required type="number" min="0" step="0.000001" placeholder="CIF USD" className={input}/><input name="defaultProfitPct" required type="number" min="0" max="99.99" step="0.01" defaultValue="5" placeholder="Default margin %" className={input}/><input name="inwardClearanceCharge" required type="number" min="0" step="0.01" defaultValue="0" placeholder="Inward clearance" className={input}/><input name="storageRate" required type="number" min="0" step="0.0001" defaultValue="0" placeholder="Storage / CBM / day" className={input}/><input name="storageDays" required type="number" min="0" step="1" defaultValue="0" placeholder="Storage days" className={input}/><select name="supplierId" className={input}><option value="">No supplier</option>{(suppliers ?? []).map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select><input name="supplierMop" placeholder="Supplier MOP" className={input}/><input name="supplierCreditDays" required type="number" min="0" step="1" defaultValue="0" placeholder="Supplier credit days" className={input}/><button className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-medium text-white">Add Product</button>
    </form></section>

    <section className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full min-w-[1450px] text-sm"><thead className="border-b bg-zinc-50"><tr><th className="px-3 py-3 text-left">Product</th><th className="px-3 py-3 text-left">Supply</th><th className="px-3 py-3 text-right">Pack kg</th><th className="px-3 py-3 text-right">CIF USD</th><th className="px-3 py-3 text-right">Margin %</th><th className="px-3 py-3 text-right">Inward</th><th className="px-3 py-3 text-right">Storage</th><th className="px-3 py-3 text-right">Days</th><th className="px-3 py-3 text-left">Supplier</th><th className="px-3 py-3 text-left">MOP</th><th className="px-3 py-3 text-right">Credit</th><th className="px-3 py-3">Active</th><th className="px-3 py-3"/></tr></thead><tbody className="divide-y">
      {(products ?? []).map((product) => <tr key={product.id}><td colSpan={13}><form action={updateProduct} className="grid grid-cols-[1.6fr_1fr_.7fr_.9fr_.8fr_.9fr_1fr_.6fr_1.2fr_1fr_.7fr_.5fr_.7fr] items-center gap-2 px-3 py-3"><input type="hidden" name="productId" value={product.id}/><input name="name" defaultValue={product.name} className={input}/><input name="supplyType" defaultValue={product.supply_type} className={input}/><input name="packSizeKg" type="number" min="0.01" step="0.01" defaultValue={Number(product.pack_size_kg)} className={input}/><input name="cifRateUsd" type="number" min="0" step="0.000001" defaultValue={Number(product.cif_rate_usd)} className={input}/><input name="defaultProfitPct" type="number" min="0" max="99.99" step="0.01" defaultValue={Number(product.default_profit_pct)} className={input}/><input name="inwardClearanceCharge" type="number" min="0" step="0.01" defaultValue={Number(product.inward_clearance_charge)} className={input}/><input name="storageRate" type="number" min="0" step="0.0001" defaultValue={Number(product.storage_rate ?? 0)} className={input}/><input name="storageDays" type="number" min="0" step="1" defaultValue={Number(product.storage_days)} className={input}/><select name="supplierId" defaultValue={product.supplier_id ?? ""} className={input}><option value="">No supplier</option>{(suppliers ?? []).map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select><input name="supplierMop" defaultValue={product.supplier_mop ?? ""} className={input}/><input name="supplierCreditDays" type="number" min="0" step="1" defaultValue={Number(product.supplier_credit_days)} className={input}/><span className="text-center text-xs">{product.active ? "Yes" : "No"}</span><button className="rounded-lg bg-zinc-900 px-3 py-2 text-xs font-medium text-white">Save</button></form><div className="flex justify-end border-t px-3 pb-2"><form action={toggleProduct}><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="active" value={String(product.active)}/><button className="text-xs text-zinc-500 hover:text-zinc-900">{product.active ? "Deactivate" : "Activate"}</button></form></div></td></tr>)}
    </tbody></table></section>
  </div>;
}
