import { requireUser } from "@/lib/auth/permissions";
import { createAdminClient } from "@/lib/supabase/admin";
import { createCustomer, toggleCustomer, updateCustomer } from "./actions";

export default async function CustomersAdminPage() {
  const { profile } = await requireUser();
  if (profile?.role !== "finance_admin") throw new Error("Forbidden");
  const { data: customers, error } = await createAdminClient().from("customers").select("id, name, code, email, phone, region, address, tax_registration_no, notes, active").order("name");
  if (error) throw new Error(error.message);
  const input = "rounded-lg border px-2.5 py-2 text-sm";
  return <div className="p-8"><div className="mb-8"><h1 className="text-2xl font-semibold">Customers</h1><p className="mt-1 text-sm text-zinc-500">Maintain customer master data used by quotations and customer-specific product mappings.</p></div>
    <section className="mb-8 rounded-xl border bg-white p-6 shadow-sm"><h2 className="mb-4 font-semibold">Add Customer</h2><form action={createCustomer} className="grid gap-3 md:grid-cols-4 lg:grid-cols-6"><input name="name" required placeholder="Name" className={input}/><input name="code" placeholder="Code" className={input}/><input name="email" type="email" placeholder="Email" className={input}/><input name="phone" placeholder="Phone" className={input}/><input name="region" placeholder="Region" className={input}/><input name="taxRegistrationNo" placeholder="Tax registration no." className={input}/><input name="address" placeholder="Address" className={`${input} lg:col-span-2`}/><input name="notes" placeholder="Notes" className={`${input} lg:col-span-2`}/><button className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-medium text-white">Add Customer</button></form></section>
    <section className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full min-w-[1250px] text-sm"><thead className="border-b bg-zinc-50"><tr><th className="px-3 py-3 text-left">Name</th><th className="px-3 py-3 text-left">Code</th><th className="px-3 py-3 text-left">Email</th><th className="px-3 py-3 text-left">Phone</th><th className="px-3 py-3 text-left">Region</th><th className="px-3 py-3 text-left">Tax No.</th><th className="px-3 py-3 text-left">Address</th><th className="px-3 py-3 text-left">Notes</th><th className="px-3 py-3">Active</th><th className="px-3 py-3"/></tr></thead><tbody className="divide-y">{(customers ?? []).map((customer) => <tr key={customer.id}><td colSpan={10}><form action={updateCustomer} className="grid grid-cols-[1.4fr_.7fr_1.3fr_1fr_.8fr_1fr_1.5fr_1.2fr_.5fr_.6fr] items-center gap-2 px-3 py-3"><input type="hidden" name="id" value={customer.id}/><input name="name" defaultValue={customer.name} className={input}/><input name="code" defaultValue={customer.code ?? ""} className={input}/><input name="email" defaultValue={customer.email ?? ""} className={input}/><input name="phone" defaultValue={customer.phone ?? ""} className={input}/><input name="region" defaultValue={customer.region ?? ""} className={input}/><input name="taxRegistrationNo" defaultValue={customer.tax_registration_no ?? ""} className={input}/><input name="address" defaultValue={customer.address ?? ""} className={input}/><input name="notes" defaultValue={customer.notes ?? ""} className={input}/><span className="text-center text-xs">{customer.active ? "Yes" : "No"}</span><button className="rounded-lg bg-zinc-900 px-3 py-2 text-xs font-medium text-white">Save</button></form><div className="flex justify-end border-t px-3 pb-2"><form action={toggleCustomer}><input type="hidden" name="id" value={customer.id}/><input type="hidden" name="active" value={String(customer.active)}/><button className="text-xs text-zinc-500 hover:text-zinc-900">{customer.active ? "Deactivate" : "Activate"}</button></form></div></td></tr>)}</tbody></table></section>
  </div>;
}
